apiVersion: v1
kind: Secret
metadata:
  name: reactjs-sample-image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwOi8vc2FzYS5jb20vcmVhY3Rqcy1zYW1wbGUiOnsidXNlcm5hbWUiOiJzYXNhcyIsInBhc3N3b3JkIjoic2FzIiwiYXV0aCI6ImMyRnpZWE02YzJGeiJ9fX0=
